# Generated by Django 6.0.6 on 2026-07-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Italian', 'Italian'), ('Fast Food', 'Fast Food'), ('Dessert', 'Dessert'), ('Salad', 'Salad'), ('Mandi', 'Mandi'), ('Drinks', 'Drinks')], default='Indian', max_length=20),
        ),
    ]
